# Generated by Django 2.2.24 on 2021-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=225)),
                ('phoneNumber', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('message', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='News1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=225)),
                ('body', models.CharField(max_length=2000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
