# Generated by Django 2.2.24 on 2021-09-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrippleG', '0002_auto_20210906_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
