# Generated by Django 2.2.24 on 2021-09-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maldini', '0002_products_productcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('productcode', models.CharField(max_length=225, null=True)),
                ('gmail', models.CharField(max_length=225, null=True)),
                ('address', models.CharField(max_length=225, null=True)),
                ('phonenumber', models.CharField(max_length=225, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
